config/routes.rb
Rails.application.routes.draw do
	root :to => 'lists#index'
  devise_for :users
	resources :pins do
	  collection do
	    get "load_images"
	  end
	end
	
	resources :lists
	resources :list_pins
	resources :notes
	resources :friends do
	  collection do
	    get "search"
	    get "invite"
	    get "approve"
	  end
	end

end

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :user
	has_many :pins, through: :list_pins
	has_many :list_pins, inverse_of: :list, foreign_key: 'list_id'
	
	PRIVATE = 0
	FRIENDS = 1
	PUBLIC = 2
	
	def is_visible(user)
	  visible = false
	  list_user = self.user
	  if user == self.user
	    visible = true
	  elsif self.visibility == PUBLIC
	    visible = true
	  elsif self.visibility == FRIENDS && list_user.friend_with?(user)
	    visible = true
	  end
	  visible
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show, :edit, :update, :destroy]
  before_action :find_users, only: [:show, :index]
  before_action :update_recents, only: [:show]
	before_filter :authenticate_user!
  def index
    @lists = @list_user.lists.order("created_at desc").select {|list| list.is_visible(current_user)}
  end
  
  def update_recents
    if @list_is_visible
      current_user.add_recent_path(@list.id)
      recent_paths # force update
    end
  end
  
  def show
    if ! @list_is_visible
      current_user.add_recent_path(@list.id)
      flash['error'] = "You do not have permission to perform this operation."
      redirect_to :back
    end    
  end

  def new
    @list = current_user.lists.build
  end
  
  def create
    @list = current_user.lists.build(list_params)
    
    if @list.save
      redirect_to @list, notice: "Successfully created new list"
    else
      render 'new'
    end
  end
  
  def edit
    if ! @list_is_mine
      flash['error'] = "You do not have permission to perform this operation."
      redirect_to :back
    end
  rescue ActionController::RedirectBackError
    redirect_to root_path
  end
  
  def update
    if @list_is_mine
      if @list.update(list_params)
        redirect_to @list, notice: "List was successfully updated"
      else
        render 'edit'
      end
    else
      flash['error'] = "You do not have permission to perform this operation."
      redirect_to :back
    end
  rescue ActionController::RedirectBackError
    redirect_to root_path
  end
  
  def destroy
    if @list_is_mine
      @list.destroy
      redirect_to root_path
    else
      flash['error'] = "You do not have permission to perform this operation."
      redirect_to :back
    end
  rescue ActionController::RedirectBackError
    redirect_to root_path
  end
  
  private
  
  def list_params
    params.require(:list).permit(:title, :description, :visibility)
  end
  
  def find_users
    @current_user = current_user
    @list_user = current_user
    if params.include? :user_id
      @list_user = User.find(params[:user_id])
    end
    @list_user_is_me = @list_user == current_user
  end
  
  def find_list
    @list = List.find(params[:id])
    @list_pins = @list.list_pins
    @list_is_mine = (@list.user.id == current_user.id)
    @show_notes = params.has_key?("secret") ? true : ! @list_is_mine
    @list_is_visible = @list.is_visible(current_user)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.haml
= simple_form_for @list, html: { multipart: true } do |f|
	- if @list.errors.any?
		#errors
			%h2 
			= pluralize(@list.errors.count, "error")
			prevented this list from being saved
			%ul
				- @list.errors.full_messages.each do |msg|
					%li= msg
	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.input :description, input_html: { class: 'form-control' }
		
	.form-group
		= f.input :visibility, default: "Private", collection: [["Private", 0], ["Friends", 1], ["Public", 2]], input_html: { class: 'form-control' }
		
	= f.button :submit, class: "btn btn-primary"

app/views/lists/_list_pin_note.html.haml
.notes
  - list_pin.notes.each do |note|
    .panel.panel-default
      .panel-heading
        - if note.kind == 2
          .bg-success
            %b= "#{note.user.nickname}:"
            = note.kind == 1 ? "Note" : "Claim"
            = "(#{time_ago_in_words(note.created_at)} ago)"
        - else
          .bg-info
            %b= "#{note.user.nickname}:"
            = note.kind == 1 ? "Note" : "Claim"
            = "(#{time_ago_in_words(note.created_at)} ago)"
      .panel-body
        = markdown(note.body)
      .panel-footer
        - if note.user_id == @current_user.id
          = link_to "Delete", note_path(note), method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-primary"
      
  .panel.panel-default
    .panel-heading
      %b New note
    .panel-body
      - note = Note.new
      .form-inline.new_note_form
        = simple_form_for note do |f|
          %p
            = f.input_field :body, label: false
          %p
            = f.input :kind, collection: [["Note", 1], ["Claim", 2]], label: false, default: "Note"
            = f.input_field :list_pin_id, :as => :hidden, :value => "#{list_pin.id}"
            = f.button :submit, "Post", class: "btn btn-primary"

app/views/lists/edit.html.haml
.col-md-6.col-md-offset-3
	%h1 Edit List
	= render 'form'
	= link_to "Cancel", list_path

app/views/lists/index.html.haml
- if @list_user_is_me
  %h1 Your lists
- else
  %h1= "#{@list_user.nickname}'s lists"
- if @lists.blank?
  - if @list_user_is_me
    .create_something_prompt
      = link_to "Create a list to store pins!", new_list_path
  - else
    .create_something_prompt
      None
- else
  - @lists.each do |list|
    #lists
      .list.box
        %span.list_name= link_to list.title, list
        - if @list_user_is_me
          %span.list_controls= link_to "Edit", edit_list_path(list)
          %span.list_controls= link_to "Delete", list_path(list), method: :delete, data: { confirm: "Are you sure?" }

app/views/lists/new.html.haml
.col-md-6.col-md-offset-3
	%h1 New List
	= render 'form'

app/views/lists/show.html.haml
- if @list_is_mine
  %h1= @list.title
- else
  %h1= "#{@list.title} (#{@list.user.nickname})"
%p= markdown(@list.description)
%p
  Last updated
  = time_ago_in_words @list.updated_at
  ago
- if @list_pins.blank?
  - if @list_is_mine
    .create_something_prompt
      = link_to "Create a pin!", new_pin_path
  - else
    .create_something_prompt
      None
- else
  #pins.transitions-enabled
    - @list_pins.each do |list_pin|
      .box.panel.panel-default
        .panel-header
          .pin_image_in_list
            - if ! list_pin.pin.image.blank?
              = link_to (image_tag list_pin.pin.image_remote_url()), list_pin.pin.url, :target => "_blank"
        .panel-body
          %h1= link_to list_pin.pin.title, list_pin.pin.url, :target => "_blank"
          %p= markdown(list_pin.pin.description)
        .panel-footer
          .row
            .col-md-12
              = link_to "View pin", list_pin.pin
              - if @list_is_mine
                .btn-group
                  = link_to "Edit", edit_pin_path(list_pin.pin), class: "btn btn-default"
                  = link_to "Delete", pin_path(list_pin.pin), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
              - if @show_notes
                = render :partial => 'list_pin_note', :locals => {:list_pin => list_pin}